### ISSUE TITLE
Compatibility with other mods

### ISSUE THREAD

**Issue by N3ROO** [sekelsta/horse-colors#11]
`sekelsta.horse_colors.client.HorseGui` should extend `net.minecraft.client.gui.screen.inventory.HorseInventoryScreen`. Then you can override the functions with the ones that you already coded. It will improve the compatibility with other mods that will still be able to use `HorseInventoryScreen` while your mod is loaded.

Context: My horse statistics mod is using the `HorseInventoryScreen` class to get the data. But when your mod is loaded, the horse screen is replaced by yours which breaks some features of my mod.

**Comment by sekelsta** [comment]
Those private fields are a pain, but alright.

**Comment by sekelsta** [comment]
This is released as of yesterday (version 1.5.0)

**Comment by N3ROO** [comment]
Thanks for your work!
