### ISSUE TITLE
Config is crazy

### ISSUE THREAD

**Issue by ChaoticSanity** [sekelsta/horse-colors#12]
So at first, the config in Notepad was normal. Then it looks like this... 
![Screenshot (43)](https://user-images.githubusercontent.com/74507720/99193482-375dfd80-2747-11eb-99c5-dde4c4c76c15.png)
Is there a way to make it look... legible, so I can understand it? I just want to make my horses get bigger as they grow ;^;

**Comment by sekelsta** [comment]
Have you checked that you're editing the config file (horse_colors-common.toml) and not the jar file?

**Comment by ChaoticSanity** [comment]
Oh, I think I forgot the last step. Sorry to waste your time.
