### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Ivyy23** [sekelsta/horse-colors#14]
![Image 2020-12-06 at 12 12 AM](https://user-images.githubusercontent.com/75556931/101272167-bc8d6e80-3757-11eb-9d9e-6b551bc68eac.jpg)
It wont let me use the mod :(

**Comment by sekelsta** [comment]
It's saying that if you want to run the 1.16.3/1.16.4 version, you need Forge for 1.16.3 or 1.16.4. If you want to stay on 1.15, use the 1.15 version of the mod.
