### ISSUE TITLE
A small bug

### ISSUE THREAD

**Issue by sxlbxr** [sekelsta/horse-colors#15]
So I love this mod and I'm playing with it nonstop since I downloaded it and I found a small bug recently:
When you fly with Elytras and aim a Horse that is too small to ride, you can ride it by right clicking just as a normal horse as long as you dont touch the floor. You cant control them anyways, since you cant saddle them, but I found this and wantet you to know this!

**Comment by sekelsta** [comment]
It's happening because the player's hitbox is much smaller while flying with an elytra. It doesn't seem to be causing any real problems so I'll leave it for now, but I'll keep it in mind. Thank you for letting me know.
