### ISSUE TITLE
Horse Genders Not Showing?

### ISSUE THREAD

**Issue by HendersonT** [sekelsta/horse-colors#16]
Not certain I am looking for the right thing, or I set it up correctly, but I enabled horse genders on a server that previously did not have horse genders. I can't seem to find any indication of horse gender in their inventory gui, and the names on unnamed horses still just says "horse." To ensure it wasn't just affecting horses that previously existed I went into creative and hatched some spawn eggs. Genders seem to otherwise be working though, with pregnancy, same genders unable to breed, etc. 
![Screenshot (44)](https://user-images.githubusercontent.com/46498198/105234218-286d4000-5b28-11eb-8407-ad1b80e7df43.png)
Screenshot just to show inventory screen on unnamed horse spawned from an egg after the config change. Is there maybe an issue with switching genders to on after a world was created?

**Comment by sekelsta** [comment]
Did you change the config setting on the client side? Without that it won't know to render the icon.

**Comment by sekelsta** [comment]
I am closing this with the assumption that your client and server config files do not match. If you are sure that they match and this is still not working, feel free to reopen it.

**Comment by HendersonT** [comment]
This was indeed the issue. The reason I struggled to resolve it however was because forge/curseforge keeps on resetting config options after they are changed, any idea what might cause this? Or how to fix it? It isn't an issue on my private instance, but my modpack users aren't recieving my config changes which is crazy to me.

**Comment by sekelsta** [comment]
How is your modpack set up? Does it have a default config included?

**Comment by HendersonT** [comment]
I don't think so? I export it with the config folder, but the defaultconfigs folder is empty and I don't export it. I'm not familiar with that though if it is different from a normal config. I usually just send the config overrides and the mod list. The weird thing is, it appears to download the new configs, but as soon as the game is launched it reverts to the old configs. Same if I edit the configs within the version of the pack I download from curse. 

Thanks for the help by the way, and I really appreciate your mod. I am in biotech by profession and it is really cool to have a fun way to apply the old genetics textbook and use quantitative genetics in a casual setting. I've got spreadsheets and everything.

**Comment by sekelsta** [comment]
Sounds like you've got at least some sort of config included, then. I'm not sure what's going on. It could be a problem with the curseforge launcher, or with the modpack. I'd recommend trying the feed the beast launcher or multimc and seeing if the problem persists, or try a different modpack and see if it's doing the same thing with the configs.
