### ISSUE TITLE
No Enable Horse Sizing in the Config

### ISSUE THREAD

**Issue by StrwbrryShrtcke** [sekelsta/horse-colors#17]
Any other version after 1.12.2 works with the different sizing, but in 1.12.2, at least for me, There is nothing in the in game or actual config file. Played through CurseForge mod loader.

**Comment by sekelsta** [comment]
Support for 1.12 ended in October, but sizes were not added until mod version 1.5.0 in December. Of course there are no sizes in 1.12. It is clearly stated on the Curseforge page that sizes were added in version 1.5.0.
