### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by southena** [sekelsta/horse-colors#19]
Hi! I can't see the horse gender with or without the hwyla mod, and when I try to generate colored horses, I always get the same horse cape and size.

I'm in 1.16.3

**Comment by sekelsta** [comment]
Have you enabled genders in the config? If you're in multiplayer, are genders enabled on both the server and your client?

**Comment by southena** [comment]
It's a server hosted by me. I changed the genders thing and the genders are not seen

**Comment by sekelsta** [comment]
It sounds like the genders are enabled on the server but not the client. I'd recommend checking the config on the client side and enabling genders there as well.
