### ISSUE TITLE
Not an issue, question

### ISSUE THREAD

**Issue by BadgerBlues** [sekelsta/horse-colors#20]
Hey, I know it isnt an issue but a question, but I was wondering if you're gonna backport newer versions to 1.12.2 again? It's what I mainly play on and it would just be cool to have the newer stuff in. Sorry if I missed something on the curseforge page that said you wouldn't:)

**Comment by sekelsta** [comment]
No. There's now a wiki page with this info [here](https://github.com/sekelsta/horse-colors/wiki/Supported-Versions).
