### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by asheb617** [sekelsta/horse-colors#21]
After downloading ive noticed when I spawn horses, they are see through? The colors and everything are fine, but they are transparent, I’ve tried uninstalling and reinstalling, and restarting my computer, but they all spawn transparent.
![image](https://user-images.githubusercontent.com/79441535/108675156-65747b80-74b4-11eb-87fb-4a03480cbd03.jpg)

**Comment by sekelsta** [comment]
What shaders do you have installed? This is a [known problem](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/127) with Sildur's.
