### ISSUE TITLE
Can't find config file :/

### ISSUE THREAD

**Issue by claryak1** [sekelsta/horse-colors#22]
Hi! So I went through minecraft, opened the mod file pack, and for the life of me I can't find the config file horse_colors-common.toml. I've tried everything, I even re-downloaded the mod but it's no where to be found in my files (I have a brand new Dell, so I don't think it's my computer's fault)

I can open the jar file just fine as well. The mod runs really well in minecraft, and I haven't had any technical difficulties with it. I just wanted to add genders and longer pregnancy periods for my horses, but I can't do that if I can't even locate the configurations haha.

This is most likely my own fault, and I'm not sure if I can even get help for this, but I figured I should try

**Comment by sekelsta** [comment]
Can you find configuration files for other mods? If so, it should be there with them. If not, I'd recommend following the instructions at [Wiki: Configuration](https://github.com/sekelsta/horse-colors/wiki/Configuration). You've found the jar file, that's good. It's in .minecraft/mods. If you go one folder up, that should take you to .minecraft, and from there you should be able to find the config folder.

Oh and in case you're on 1.12, in that version it's named horse-colors.cfg instead.
