### ISSUE TITLE
The game crashed

### ISSUE THREAD

**Issue by bluuena** [sekelsta/horse-colors#26]
![Ekran Görüntüsü (3)](https://user-images.githubusercontent.com/83607404/116915639-f1451980-ac54-11eb-8c4a-fc981f9ea02f.png)
 
My game crashes whenever i try to spawn a horse. I've tried to delete and download the mod again and even tried to uninstall and install minecraft but nothing worked so far. I really would appreciate some help.

**Comment by sekelsta** [comment]
What mod version are you using? E.g. 1.5.9, 1.6.0?

**Comment by bluuena** [comment]
I'm currently using 1.16.5

**Comment by sekelsta** [comment]
That is the Minecraft version. What version of horse_colors is installed?

**Comment by bluuena** [comment]
It's the last version updated on april 14th but I've had this problem with other versions as well mainly after 1.14.2

**Comment by sekelsta** [comment]
I believe it's a bug involving Turkish locale. Will fix!
(https://mattryall.net/blog/the-infamous-turkish-locale-bug)

**Comment by bluuena** [comment]
That's unfortunate but thanks a lot. I really appreciate it

**Comment by sekelsta** [comment]
This should be fixed by 75b583ac9d790843c29a79811349e62923b4cd14. The new file is here: https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics/files/3297524

Let me know if it works!

**Comment by bluuena** [comment]
I just had the time to try it out and it works thank you so much
