### ISSUE TITLE
Loaded but will not play

### ISSUE THREAD

**Issue by ccbelle** [sekelsta/horse-colors#32]
We have downloaded forge and been successful with 3 other mods. This mod looks as if it’s loaded but none of the horse colors have changed. We are using the most updated version of each.
What to do?

**Comment by SnowDragon064** [comment]
Are you sure its not vanilla horses you're seeing? If you're using a version that is 1.13 or higher, the models will be the same as vanilla 1.12 horses. The modded horses also use a different spawn egg(brown)

**Comment by sekelsta** [comment]
As SnowDragon said, you are most likely seeing vanilla horses. To find the horses with genetics, you can explore new chunks, or edit the config to enable conversion of vanilla horses into genetic horses. I'm working on a way to make this better.
