### ISSUE TITLE
Horse Taking Damage on Dismount

### ISSUE THREAD

**Issue by xmsteele23** [sekelsta/horse-colors#39]
Horse takes damage (half a heart) every time you dismount. I have tested with removing all baubles, and moving location. Not sure the cause.

**Comment by sekelsta** [comment]
This isn't happening when I play. Can you send me a list of mods you're using? Or, better yet, see if it still happens without other mods installed?

**Comment by xmsteele23** [comment]
![Capture](https://user-images.githubusercontent.com/83218860/130329228-a74d187e-d15f-4364-bdff-52e55b4adf2c.PNG)

**Comment by sekelsta** [comment]
Haven't been able to repro this due to the large number of mods, going to assume either it's a mod interaction or the ceiling is too low.

**Comment by theOverture** [comment]
I know I'm mighty late, but I'm pretty sure this is caused by "Stupid Horse Stand Still"
I had the same problem and removing it seemed to work.
