### ISSUE TITLE
Neck glitch

### ISSUE THREAD

**Issue by xmsteele23** [sekelsta/horse-colors#40]
Occasionally the neck of the horse moves entirely out of place.
![2021-08-18_14 47 58](https://user-images.githubusercontent.com/83218860/129955092-0302a805-c5e0-4a5e-8e83-5c84f9536a06.png)
![2021-08-18_14 48 09](https://user-images.githubusercontent.com/83218860/129955093-8860f087-aebb-4237-9771-3e181a43a906.png)

**Comment by sekelsta** [comment]
Are you using any mods that affect AI?

**Comment by sekelsta** [comment]
Closing as stale. Most likely another mod is affecting "look at" logic.
