### ISSUE TITLE
Can not open config

### ISSUE THREAD

**Issue by XxMistSniperxX** [sekelsta/horse-colors#42]
Tried to enable horse gender, but was not able to open config. It is greyed out.

**Comment by tmreschke** [comment]
I can open the config but it is in a different language

**Comment by boocoupbaby** [comment]
unable to enable horse genders. anyone know how to?

**Comment by sekelsta** [comment]
In-game config is not being added as a feature unless Forge provides support. See here for how to edit the config:
https://github.com/sekelsta/horse-colors/wiki/Configuration
