### ISSUE TITLE
Mod File horse_colors-1.18.1-1.7.1.jar needs language provider javafml:39 or above to load

### ISSUE THREAD

**Issue by GracefullyArdent** [sekelsta/horse-colors#45]
game refuses to load due to 1.18.1 files missing for this mod. 

Failure message: Mod File horse_colors-1.18.1-1.7.1.jar needs language provider javafml:39 or above to load
		We have found 38

**Comment by sekelsta** [comment]
Your Forge version is for 1.18,, not 1.18.1. You can get the right version here: 
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.18.1.html
