### ISSUE TITLE
1.12.2-Translucent Horses

### ISSUE THREAD

**Issue by UberbeastX** [sekelsta/horse-colors#47]
![2022-02-06_14 57 59](https://user-images.githubusercontent.com/74433319/152707024-9825ad82-d48b-43a9-8bc0-a86b780a2cac.png)

I have no idea what's wrong and was wondering if you could tell me what could be causing the horses to be translucent like this.

**Comment by sekelsta** [comment]
What shaders are you using, and which versions? I know Sildur's shaders 1.28 can cause this issue but Sildur's shaders 1.29 works fine.

**Comment by UberbeastX** [comment]
I have no shaders installed but if that's what causes it. Maybe it's related to a mod I have installed that has to do with shading like betweenlands or disillusioned or something like that.

**Comment by sekelsta** [comment]
Dropping support for 1.12.2 - this is probably related to another mod, though.

**Comment by UberbeastX** [comment]
Dang I just found out today that it was the dynamic stealth  mod since I finally had enough time to just try and troubleshoot it. I understand though working on like 3 versions at once sounds like it would be tiring.
