### ISSUE TITLE
Possible conflict with the occult mod.

### ISSUE THREAD

**Issue by Methlon** [sekelsta/horse-colors#48]
Long story short, the genetics horses aren't treated as normal horses, and can't be used as horses for... a sacrifice.
Not sure if this is something you'd care to look into.

No regular horses appear in the wild, either.  All the genetic ones.

As far as everything else goes, the mod works great.
Just this one lil bit causing a conflict, no crashes or anything insane, just something that is not recognized by this mod.

Anyways, thanks for your time.
Dave

**Comment by sekelsta** [comment]
There's a config setting to allow vanilla horses to spawn. Alternately, you could get in touch with that mod's team about compatibility. Or if you want to take a stab at it yourself, I think the file to change might be 
https://github.com/klikli-dev/occultism/blob/59b44386bfe59da9ddd9102459965f8c66f46f58/src/main/resources/data/forge/tags/entity_types/horses.json
and
