### ISSUE TITLE
[1.18.2] Worker-Main-14/ERROR - duplicate key

### ISSUE THREAD

**Issue by Maypul** [sekelsta/horse-colors#52]
Hello!
Forge: 40.1.0
Mod version: 1.4.3
MC: 1.18.2
It seems whenever I add this mod to the modlist, In logs I can see following error:
[19:14:58] [Worker-Main-14/ERROR] [minecraft/Util]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/common/animals]' to registry
Just in case it is something worth to note, I am reporting it.

**Comment by sekelsta** [comment]
Thanks for reporting this. The error message is a side effect of the way this mod makes custom horse entities spawn in village structures. world.Spawns.java:changeVillageAnimals() is overwriting this registry entry on purpose. Unfortunately I don't think there's anything I can reasonably do to prevent it from printing this error, but at least it is not a sign of anything being wrong.
