### ISSUE TITLE
[1.18.1] Horses are rendered as pigs when Optifine is installed

### ISSUE THREAD

**Issue by JonPhno** [sekelsta/horse-colors#53]
As the title says, horses are rendered as pigs since I installed Optifine. This is on a multiplayer server and even when no shaders or texture pack activated the horses are still pigs. Other players without Optifine see the horses fine.

![image](https://user-images.githubusercontent.com/22062595/168701224-4ba4acf9-f529-4b29-bcd5-95c95eed61df.png)

OptiFine_1.18.1_HD_U_H4.jar

**Comment by sekelsta** [comment]
This is most likely a problem with optifine. You can try opening an issue on it's bug tracker: https://github.com/sp614x/optifine/issues
Good luck!
