### ISSUE TITLE
MC 1.16.5 Horses not recognized as "horse" leading to intercompatibility issues with other mods

### ISSUE THREAD

**Issue by codec-d** [sekelsta/horse-colors#54]
using Relics "horse flute" item works on vanilla horses however horses from realistic horse genetics are not recognized the same way as vanilla horses leading to no compatibility

**Comment by sekelsta** [comment]
1.16.5 is no longer being updated, and this would need to be fixed on their side anyway. RHG horses are instances AbstractHorseEntity but not HorseEntity. If they expand their flute to also work on donkeys and mules, it should also be able to affect these horses.
