### ISSUE TITLE
Can't breed the horses

### ISSUE THREAD

**Issue by maddygreen54** [sekelsta/horse-colors#61]
Hi! I downloaded the 19.2 version of your mod yesterday. All aspects of the mod are running perfectly except for the breeding feature. When I try breeding 2 of the horses (Spawned from the egg for your mod, tamed, opposite genders, and with golden apples) they act like they're breeding, but no foal appears. I still collect the experience from it as well. I've tried this with several different pairings of horses. I'm not sure what could be causing this?

**Comment by sekelsta** [comment]
That would be the pregnancy feature. Wait a day, and the foal will appear. Meanwhile, you can check progress by looking at the mare's inventory. In the top right corner, if she's pregnant, there will be a little bar that fills up over time.

**Comment by maddygreen54** [comment]
Oh my goodness I'm sorry, I didn't realize that was a feature. Thanks for the info!
