### ISSUE TITLE
game crashes when I try to spawn horse

### ISSUE THREAD

**Issue by goopybby** [sekelsta/horse-colors#62]
ive already took out the mod and the deleted the config and downloading the file again but it still does this. i dont think its any of my mods because they are just biomes o plenty and the seasons o plenty one. could it be a resource pack interfering? I also downloaded another version of the 19.3 file and still does it.

**Comment by sekelsta** [comment]
Please send the crash log

**Comment by sekelsta** [comment]
Closing as inactive + unable to reproduce
