### ISSUE TITLE
horses not generating in 1.20.1 /errors in logs

### ISSUE THREAD

**Issue by smmmadden** [sekelsta/horse-colors#68]
Forge 47.1.39
Horses 1.20.1-11.4
latest logs: https://pastebin.com/uprVcXhb
At startup there is an issue with one of the recipes on line 73
[20Jul2023 10:34:05.853] [main/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe horse_colors:netherite_horse_armor_smithing
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'minecraft:smithing'
Then as I'm in the game moving around, periodically the server threw exceptions when trying to generate the horses.  Currently, mod is not working at all in 1.20.1 so I had to remove it.

**Comment by sekelsta** [comment]
Fixed by b510f469275c3759b9057ccc5364dc681d7f80c4. Thank you for the detailed report.

**Comment by smmmadden** [comment]
any eta on when you'll post the update with this fix?

**Comment by sekelsta** [comment]
Here: https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics/files/4657479
