### ISSUE TITLE
Compatibility with horse food for Farmer's Delight

### ISSUE THREAD

**Issue by BlackAures1** [sekelsta/horse-colors#73]
You can add the `horse_feed_users` and `horse_feed_tempted` tag so modpack creators don't have to add this themselves.

![image](https://github.com/sekelsta/horse-colors/assets/43911230/7494f03e-7c64-41d5-9fb2-db6177d515be)

**Comment by sekelsta** [comment]
Fixed by 38daf67929984c2cc46df1cc59418db678d6ec59
