### ISSUE TITLE
Gene Book not working

### ISSUE THREAD

**Issue by gwynhefar** [sekelsta/horse-colors#74]
When I right click on a horse with the gene book, I end up mounting the horse instead.  Control-Right Click opens up the horse inventory.  The book doesn't change, and I can't open it.  The game output reads "[23:19:17] [Server thread/INFO] [STDOUT]: [sekelsta.horse_colors.item.GeneBookItem:func_77659_a:94]: Gene book has invalid NBT"

Help!

**Comment by sekelsta** [comment]
Use a vanilla book instead. There's a reason they're not available in the creative inventory.
